version: "3"
services:
  eurekaserver1:
    image: wannshan/eureka-server:1.3
    ports:
      - "8761:8760"
    environment:
      - spring.profiles.active=peer1

  eurekaserver2:
    image: wannshan/eureka-server:1.3
    ports:
      - "8762:8760"
    environment:
      - spring.profiles.active=peer2